### ISSUE TITLE
Frozen inboxnoticestream

### ISSUE THREAD

**Issue by chimo** [chimo/gs-rediscache#1]
At the moment, enabling this plugin (and I'm suspecting any other "cache" plugins) freezes users' `inboxnoticestream` (i.e.: ":nickname/all" endpoint) to whatever content we first cache and never gets updated.

I believe this is due to the fact that [it's using CachingNoticeStream](https://github.com/chimo/social/blob/sn.chromic.org/lib/inboxnoticestream.php#L58) but that cache doesn't get invalidated on [relevant notice insert/delete](https://github.com/chimo/social/blob/sn.chromic.org/classes/Notice.php#L1123).

We might be able to fix this by catching the [EndNoticeWhoGets](https://github.com/chimo/social/blob/sn.chromic.org/classes/Notice.php#L1530) event, checking what's in there and blowing away the cache for those. Ideally, this would be done upstream so that it doesn't need to be done in every Cache plugin.

Note: the fact that `inboxnoticestream` [uses the same cache key](https://github.com/chimo/social/blob/sn.chromic.org/lib/inboxnoticestream.php#L58) ('profileall') for all profiles might also be a problem. If so, we could append ":$target->getID()" to it, as done [in other places](https://github.com/chimo/social/blob/66910cdc00fe1cbfebc1b24a33c8256e53bce68f/plugins/Event/lib/eventsnoticestream.php#L53).

**Comment by mitchellurgero** [comment]
couldn't you ignore the cache for that particular route? that way it will just update as needed?

**Comment by chimo** [comment]
That's what I'm doing on my local instance at the moment (I reverted [this commit](https://git.gnu.io/gnu/gnu-social/commit/36a55d84363e69bf08da38e524f7d33063c2743a) specifically, but that requires changes to upstream files (afaict).

Ultimately it'd be nice to cache inbox streams as well thought so that's what I'm aiming for.  :)

**Comment by chimo** [comment]
On my local instance, I reverted [this commit](https://git.gnu.io/gnu/gnu-social/commit/36a55d84363e69bf08da38e524f7d33063c2743a) but detecting the inboxnoticestream route and forcing a cache-miss for that is an interesting idea for the short term. I'll look into it.

Ultimately it'd be nice to cache inbox streams as well thought so that's what I'm aiming for for the long term. :)

**Comment by mitchellurgero** [comment]
Why not instead use nginx caching?
